# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        node-version: [19.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm ci
      - run: npm run build
      - run: npm run test

  publish:
    name: Publish to GitHub Packages
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{ github.repository_owner }}"

      - name: Install Dependencies
        run: npm ci

      - name: Set package.json package name
        run: npm pkg set name=@${{ github.repository_owner }}/${{ github.repository }}

      - name: Set package.json package version
        #   run: npm pkg set version=$(git rev-parse --short HEAD)
        run: npm pkg set version=$(date +%s)

      - name: Build
        run: npm run build

      - name: Set registry url
        run: npm config set -l registry https://npm.pkg.github.com

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
